name: Deploy Migrations to Staging

on: [push]

jobs:
  deploy:
    name: Test, lint, backup and push migrations to staging
    runs-on: ubuntu-latest
    environment:
      name: Preview – bytebuzz

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase db start

      - name: Link to staging project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: See schemas differences between local and remote
        run: supabase db diff --linked

      - name: Run lint
        run: supabase db lint --fail-on error

      - name: Run tests
        run: supabase test db

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate backup
        run: bun db:dump-remote

      - name: Upload backup to Vercel Blob
        uses: dartilesm/vercel-blob-action@v2
        with:
          source: "supabase/dump"
          destination: "db-backup-staging"
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

      - name: Push migrations to staging
        run: supabase db push
